[package]
name = "tinypointers"
version = "0.2.0"
edition = "2021"
authors = ["Diego Augusto"]
description = "Pointer implementations that take 8 or 16 bits."
license = "MIT"

[features]
default = ["2byteid"]
1byteid = []
2byteid = []

[dependencies]
parking_lot = "0.12.1"
